### ISSUE TITLE
项目里面差java文件

### ISSUE THREAD

**Issue by 511098425** [liuweijw/fw-cloud-framework#10]
fw-cloud-business-admin模块中差以Q开头的文件，fw-cloud-business-admin模块无法启动

**Comment by liuweijw** [comment]
以Q开头的文件都是通过querydsl插件自动生成的!  请查看相关的maven配置和项目常见问题
项目提供了一个maven配置做参考：https://github.com/liuweijw/fw-cloud-framework/wiki/07-Maven%E4%BB%93%E5%BA%93%E9%85%8D%E7%BD%AE
QueryDsl 相关学习：http://books.aying.org/querydsl_zh_CN/Tutorials/Querying%20JPA.html
