### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by gzcassan** [liuweijw/fw-cloud-framework#18]
Error:(8, 50) java: 找不到符号
  符号:   类 QWechatInfo
  位置: 程序包 com.github.liuweijw.business.wechat.domain

Error:(8, 50) java: 找不到符号
  符号:   类 QAuthInfo
  位置: 程序包 com.github.liuweijw.business.wechat.domain

Error:(7, 50) java: 找不到符号
  符号:   类 QUrlInfo
  位置: 程序包 com.github.liuweijw.business.wechat.domain

**Comment by liuweijw** [comment]
导入项目之后，编译or install 下。 Q开头的类是querydsl 插件自动生成
