### ISSUE TITLE
请问为何业务模块不添加权限控制？

### ISSUE THREAD

**Issue by lizige** [liuweijw/fw-cloud-framework#19]
请问为何业务模块不添加权限控制？

**Comment by liuweijw** [comment]
业务模块有权限的，所有服务接入是从网关（gateway）接入，通过oauth2 方式授权。  同时业务模块还增加二级权限，比如某个请求是否有权限，通过切面实现的。  现在能单独访问某业务API是因为目前部署方式将端口都开发了。
