### ISSUE TITLE
QDept, QUser这些辅助类是JPA自动生成的么，工程里并没有找到。

### ISSUE THREAD

**Issue by hepyu** [liuweijw/fw-cloud-framework#20]
如题。

**Comment by liuweijw** [comment]
QueryDsl 插件自动生成的
可以参考相关说明：https://github.com/liuweijw/fw-cloud-framework/wiki/09-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E8%A7%A3%E5%86%B3

**Comment by hepyu** [comment]
3Q~
